### PR TITLE
Ability of storing files in different directories

### LINKED ISSUE #114: Is it possible to store files in different folders(profile images/article files)
I wont to separeate files depend on section/item type. As example to have diffent folders for: profile images; news attachments; products files. Is it possible without configuring new component in config setion, per each section/item type ?

### LINKED ISSUE #119: how to config a myself path for UploadAction?
UploadAction : upload file to a default path , for example:  source/1
but some time ,I want to upload some files to other path, for example: source/other-path

### PR DESCRIPTION
**Pull request by klxdr**
closes #119
closes #114

### CODE REVIEW

**Comment by trntv** [comment]
Can you add an example to docs?

**Comment by klxdr** [comment]
readme updated

**Comment by mistermusk** [comment]
@klxdr Thanx, worked for me

**Comment by sichkarev** [comment]
Hey! Please merge this request to master.

**Comment by sichkarev** [comment]
@trntv Thank you very much Eugene! All the best!

**Pull request merged**
